title: Oakland Finish Up Weekend
tagline: Success comes with mentorship.
url: http://oaklandfinishup.com

timezone: US/Pacific

collections:
  - sections
  - mentors
  - schedule
  - quotations
  
gems:
  - jekyll-sitemap
