title: Oakland F'Up Weekend (Oakland Finish Up Weekend)
tagline: It's easy to start shit.  Let's finish it.
timezone: US/Pacific
url: http://oaklandfup.com

collections:
    - mentors
    - schedule
  

gems:
  - jekyll-sitemap
