title: Oakland Finish Up Weekend
tagline: Success comes with mentorship.
url: http://oaklandfinishup.com

timezone: US/Pacific

collections:
  - sections

google-analytics: UA-61672521-1 

gems:
  - jekyll-sitemap
