title: Oakland F'Up Weekend (Oakland Finish Up Weekend)
tagline: It's easy to start shit.  Let's finish it.
url: http://oaklandfup.com

timezone: US/Pacific

collections:
  - sections
  - mentors
  - schedule
  
gems:
  - jekyll-sitemap
